// ============================= USERS =====================================

###
POST http://localhost:3003/user/cadaster
Content-Type: application/json

{
"name": "Ricardo Ribeiro",
 "email": "rickhard@gmail.com", 
 "password": "123456",
 "role": "admin"
}

###
POST http://localhost:3003/user/cadaster
Content-Type: application/json

{
"name": "Gabrie",
 "email": "gabriel@gmail.com", 
 "password": "123456",
 "role": "normal"
}

###
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "email": "rickhard@gmail.com",
   "password": "123456"
}

//====================== BANDS ==============================

###
POST http://localhost:3003/band/register
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlY2JmMWQxLWZjOGEtNDRhYy05NWExLTg1YzJjNGU0NzBmNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzE5NTUyOCwiZXhwIjoxNjU3MjgxOTI4fQ.SXa7UDysO4EMhQO1L7ql3vPhpi-AHQ8bhuLjCexQwCg

{
"name": "Banada Teste 1",
 "photo": "Banda teste photo 1", 
 "musicGenre": "BandaTeste music 1",
 "responsible": "Banda Teste responsible 1"
}


###
GET http://localhost:3003/band/Banada Teste 1
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlY2JmMWQxLWZjOGEtNDRhYy05NWExLTg1YzJjNGU0NzBmNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzIxODM4OSwiZXhwIjoxNjU3MzA0Nzg5fQ.BVcJ8hitXwkuvZAxhn1N4ZI0jfpovX2gCW-ssR43dEE


###
POST http://localhost:3003/band/schedule/0f6e5890-c2c7-4cf2-9939-b00c094a2b49
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBlY2JmMWQxLWZjOGEtNDRhYy05NWExLTg1YzJjNGU0NzBmNiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NzIxODU3MCwiZXhwIjoxNjU3MzA0OTcwfQ.z_GHvsuXG_GNl8bvsC8AcWol_Yk6wQjPZcD9z5Fd5f0

{
   "photo": "Show photo Test 4",
   "weekDay": "SEXTA",
   "startTime": 23,
   "endTime": 5
}